name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Moon env (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libssl-dev
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"

      - name: Setup Moon env (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gcc openssl
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"

      - name: Setup Moon env (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
          irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
          "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Setup MSYS2 + MinGW + openssl (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-openssl

      - name: Post install
        run: |
          moon version --all
          moon update

      - name: Moon Check
        run: |
          moon check --target all --deny-warn --fmt
          moon check --target all --deny-warn
          moon info --target all
          git diff --exit-code

      - name: Moon Test
        run: |
          moon test --target all --deny-warn
