name: MoonBit CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MoonBit
        uses: moonbit-community/setup-moonbit@v1
        with:
          version: '0.10.3'

      - name: Check Formatting
        run: moon fmt --deny-warn

      - name: Check Info
        run: moon info --deny-warn

      - name: Build and Check
        run: moon check

      - name: Run Tests
        run: moon test
